export * from './health-check.controller';
export * from './gym.controller';
export * from './exercise.controller';
export * from './user.controller';
export * from './auth.controller';
export * from './badge.controller';
export * from './reward.controller';
export * from './challenge.controller';
export * from './leaderboard.controller';
